"""empty message

Revision ID: 12778d9a190d
Revises: d2d9ee160a21
Create Date: 2024-01-14 15:12:41.471370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12778d9a190d'
down_revision = 'd2d9ee160a21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('history')
    # ### end Alembic commands ###
